[project]
name = "cdm-task-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiobotocore==2.22.0",
    "aiofiles==25.1.0",
    "aiohttp==3.12.9",
    "aiokafka==0.12.0",
    "async-lru==2.0.5",
    "awscrt==0.27.2",
    "bidict==0.23.1",
    "cacheout==0.16.0",
    "docker==7.1.0",
    "docker-image-py==0.1.13",
    "fastapi[standard]==0.115.12",
    "htcondor==25.0.3",
    "jinja-cli==1.2.2",
    "kbase-auth-client==0.1.1",
    "marisa-trie==1.2.1",
    "motor==3.7.1",
    "python-json-logger==4.0.0",
    "requests==2.32.3",
    "sfapi-client==0.4.1",
    "uvicorn[standard]==0.34.3",
    "yarl==1.22.0",
]

[dependency-groups]
dev = [
    "boto3==1.37.3",
    "ipython==9.3.0",
    "kafka-python==2.2.10",
    "pymongo==4.13.0",
    "pytest==8.4.0",
    "pytest-asyncio==1.0.0",
    "pytest-cov==6.1.1",
]
